//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaloriesDiary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CaloriesDiaryEntities : DbContext
    {
        public CaloriesDiaryEntities()
            : base("name=CaloriesDiaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diary> Diaries { get; set; }
        public virtual DbSet<DiaryEntry> DiaryEntries { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Measure> Measures { get; set; }
    }
}
